export const ROUTES = [
  { id: "1", name: "Trafalgar" },
  { id: "3", name: "Third Line" },
  { id: "4", name: "Speers - Cornwall" },
  { id: "5", name: "Dundas" },
  { id: "6", name: "Upper Middle" },
  { id: "10", name: "West Industrial" },
  { id: "11", name: "Linbrook" },
  { id: "12", name: "Winston Park" },
  { id: "13", name: "Westoak Trails" },
  { id: "14", name: "Neyagawa" },
  { id: "15", name: "Bronte" },
  { id: "17", name: "Rebecca" },
  { id: "18", name: "West Oak Trails" },
  { id: "19", name: "River Oaks" },
  { id: "20", name: "North Service" },
  { id: "24", name: "Lakeshore" },
  { id: "26", name: "Dundas North" },
  { id: "28", name: "Glen Abbey North" },
  { id: "32", name: "Bronte - Palermo" },
  { id: "45", name: "Oakville - Mississauga Express" },
  { id: "120", name: "Burloak" },
] as const;
