export const ROUTES = [
  { id: "1", name: "Trafalgar", color: "#ff0000", foreground: "#ffffff" },
  { id: "3", name: "Third Line", color: "#246bce", foreground: "#ffffff" },
  { id: "4", name: "Speers - Cornwall", color: "#137a4b", foreground: "#ffffff" },
  { id: "5", name: "Dundas", color: "#f28a3b", foreground: "#171717" },
  { id: "6", name: "Upper Middle", color: "#7c3aed", foreground: "#ffffff" },
  { id: "10", name: "West Industrial", color: "#0f8b8d", foreground: "#ffffff" },
  { id: "11", name: "Linbrook", color: "#a05a00", foreground: "#ffffff" },
  { id: "12", name: "Winston Park", color: "#b81461", foreground: "#ffffff" },
  { id: "13", name: "Westoak Trails", color: "#ec2f8f", foreground: "#ffffff" },
  { id: "14", name: "Neyagawa", color: "#64748b", foreground: "#ffffff" },
  { id: "15", name: "Bronte", color: "#0891b2", foreground: "#ffffff" },
  { id: "18", name: "West Oak Trails", color: "#22a06b", foreground: "#ffffff" },
  { id: "19", name: "River Oaks", color: "#6d5dfc", foreground: "#ffffff" },
  { id: "20", name: "North Service", color: "#20201f", foreground: "#ffffff" },
  { id: "26", name: "Dundas North", color: "#c9342f", foreground: "#ffffff" },
  { id: "28", name: "Glen Abbey North", color: "#0f766e", foreground: "#ffffff" },
  { id: "120", name: "Burloak", color: "#d61d72", foreground: "#ffffff" },
] as const;
